version: '3.8'

services:
  db:
    image: postgres:15
    container_name: vote_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vote_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: vote_web
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vote_system
      - FLASK_APP=app
      - FLASK_DEBUG=1

volumes:
  postgres_data:
    driver: local